Made 429 Too Many Request HTTP error in `raw_call()` of `client.py` retryable
mwclient/mwclient pull request #337
Opened 2024-06-29 11:59 UTC by murolem

This prevents the program from straight-up failing, instead resorting to retries if they are enabled.

2024-07-17 16:13 UTC, RheingoldRiver commented
This lgtm - fixes a persistent problem with the lib when connecting to wikis that have CF ratelimites

2024-07-17 19:50 UTC, AdamWill commented
LGTM too, but it fails tests because the line is too long, our max is 90 chars. @murolem can you reformat? Thanks!

2024-07-17 20:02 UTC, marcfrederick commented
I think `stream.status_code != 429` would be easier to read here than `not stream.status_code == 429`. Apart from that ([and the line length](https://github.com/mwclient/mwclient/actions/runs/9723930239/job/27573012035?pr=337)), this looks good to me.

2024-08-30 10:59 UTC, marcfrederick requested changes

2024-08-30 10:59 UTC, marcfrederick commented on mwclient/client.py
> +                elif (stream.status_code < 500 or stream.status_code > 599) and not stream.status_code == 429:  # 429 is Too Many Request - this is retryable:
```suggestion
                elif (
                    (stream.status_code < 500 or stream.status_code > 599)
                    and stream.status_code != 429  # 429 Too Many Requests is retryable
                ):
```

2024-08-31 13:25 UTC, marcfrederick approved these changes
Thank you @murolem! LGTM now.

2024-08-31 13:25 UTC, merged